Mark pgm_family_string as 'inline'
Functions defined in headers need to be 'static inline', otherwise the compiler
will generate an unused-function warning for every program that includes the
header but doesn't use the function.

 In file included from /usr/include/pgm-5.3/pgm/skbuff.h:39,
                  from /usr/include/pgm-5.3/pgm/msgv.h:33,
                  from /usr/include/pgm-5.3/pgm/pgm.h:44,
                  from src/ip.cpp:53:
 /usr/include/pgm-5.3/pgm/socket.h:207:1: error: 'const char* pgm_family_string(int)' defined but not used [-Werror=unused-function]
   207 | pgm_family_string (
       | ^~~~~~~~~~~~~~~~~